# Generated by Django 3.1.5 on 2021-01-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthika', '0003_product_type_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_type',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='media/product_type'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='package_image1',
            field=models.ImageField(blank=True, default='', upload_to='media/product_type'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='package_image2',
            field=models.ImageField(blank=True, default='', upload_to='media/product_type'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='package_image3',
            field=models.ImageField(blank=True, default='', upload_to='media/product_type'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='package_image4',
            field=models.ImageField(blank=True, default='', upload_to='media/product_type'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='package_image5',
            field=models.ImageField(blank=True, default='', upload_to='media/package_im0age'),
        ),
    ]
