# Generated by Django 3.1.5 on 2021-01-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthika', '0004_auto_20210118_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type',
            name='package_image1_price',
            field=models.ImageField(blank=True, default='', upload_to='media/product_type'),
        ),
        migrations.AddField(
            model_name='product_type',
            name='package_image2_price',
            field=models.ImageField(blank=True, default='', upload_to='media/product_type'),
        ),
        migrations.AddField(
            model_name='product_type',
            name='package_image3_price',
            field=models.ImageField(blank=True, default='', upload_to='media/product_type'),
        ),
        migrations.AddField(
            model_name='product_type',
            name='package_image4_price',
            field=models.ImageField(blank=True, default='', upload_to='media/product_type'),
        ),
        migrations.AddField(
            model_name='product_type',
            name='package_image5_price',
            field=models.ImageField(blank=True, default='', upload_to='media/package_im0age'),
        ),
    ]
