# Generated by Django 3.1.5 on 2021-01-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthika', '0005_auto_20210119_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_type',
            name='package_image1_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='package_image2_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='package_image3_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='package_image4_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
