# Generated by Django 3.1.5 on 2021-01-19 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earthika', '0014_product_type_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_type',
            old_name='package_image1_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='package_image1',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='package_image2',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='package_image2_price',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='package_image3',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='package_image3_price',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='package_image4',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='package_image4_price',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='package_image5',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='package_image5_price',
        ),
        migrations.CreateModel(
            name='Product_Type_Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_image', models.ImageField(blank=True, default='', upload_to='media/product_type')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, default='', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('product_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_package', to='earthika.product_type')),
            ],
        ),
    ]
