# Generated by Django 3.1.5 on 2021-01-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthika', '0015_auto_20210119_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type_package',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='product_type_package',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
