# Generated by Django 3.1.6 on 2021-02-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthika', '0017_enquiry_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='media/product'),
        ),
    ]
